FROM node:22-alpine AS builder

WORKDIR /app

RUN apk add --no-cache curl bash
ENV BUN_INSTALL=/usr/local
RUN curl -fsSL https://bun.sh/install | bash

COPY package.json bun.lock ./
RUN bun install --frozen-lockfile
COPY . .
RUN bun run build

FROM caddy:alpine

RUN apk add --no-cache curl

COPY --from=builder /app/build /usr/share/caddy

EXPOSE 7381

CMD ["caddy", "run", "--config", "/etc/caddy/Caddyfile"]