FROM rust:1.93 as builder

WORKDIR /app

COPY Cargo.toml Cargo.lock ./
COPY src ./src
COPY DEFAULT_CONFIG.json5 ./

RUN cargo build

FROM debian:bookworm-slim

RUN apt-get update && \
    apt-get install -y ca-certificates curl && \
    rm -rf /var/lib/apt/lists/*

COPY --from=builder /app/target/debug/playback-server /usr/local/bin/

EXPOSE 9247

CMD ["playback-server"]